<?php

namespace WPGeonames;

use ErrorException;
use mysqli;
use function mysqli_errno;

if ( ! defined( 'ARRAY_K' ) )
{
    define( 'ARRAY_K', 'ARRAY_K' );
}


class WpDb
    extends
    \wpdb
{

// constants

    public const DEFAULT_TABLE_PREFIX = 'wp_';

//  public properties

    public $last_error_no = 0;

// protected properties

    protected $use_mysqli    = false;
    protected $has_connected = false;


    /**
     * WpDb constructor.
     *
     * @param  \wpdb|null  $db
     *
     * @noinspection PhpMissingParentConstructorInspection
     * @noinspection MagicMethodsValidityInspection
     */
    public function __construct( \wpdb $db = null )
    {

        global $wpdb;

        $db = $db ?? $wpdb;

        $db->flush();

        $x = get_object_vars( $db );

        /*
         $skip = array_merge(
            [
                'tables',
                'old_tables',
                'global_tables',
                'ms_global_tables',
                'incompatible_modes',
            ],
            $this->old_tables
        );
        */

        foreach ( $x as $property => &$value )
        {

            //if ( in_array( $property, $skip ) ) {
            //continue;
            //}

            if ( property_exists( $this, $property ) )
            {
                $this->$property =& $value;
            }
            else
            {
                $this->$property = $value;
            }

        }

        unset ( $value );

        foreach (
            [
                'use_mysqli',
                'has_connected',
            ] as $property
        )
        {

            $this->$property = $wpdb->__get( $property );
            $this->__set( $property, $this->$property );

        }

        if ( $wpdb instanceof \wpdb )
        {
            $wpdb = $this;
        }

    }


    public function deleteAndReplaceTablePrefix(
        $table,
        $where,
        $where_format = null
    ) {

        return parent::delete(
            static::replaceTablePrefix( $table ),
            $where,
            $where_format
        ); // TODO: Change the autogenerated stub
    }


    public function flush(): void
    {

        $this->last_error_no = 0;

        parent::flush();
    }


    public function insertAndReplaceTablePrefix(
        $table,
        $data,
        $format = null
    ) {

        return parent::insert( static::replaceTablePrefix( $table ), $data, $format );
    }


    public function prepare(
        $query,
        ...$args
    ) {

        if ( is_null( $query ) )
        {
            return;
        }

        $checkScalar = static function (
            &$arg,
            $index,
            $checkScalar = null
        ) {

            if ( is_array( $arg ) && $checkScalar !== null )
            {
                array_walk( $arg, $checkScalar );
            }
            elseif ( ! is_scalar( $arg ) && ! is_null( $arg ) )
            {

                $arg = (string) $arg;
            }
        };

        array_walk(
            $args,
            $checkScalar,
            $checkScalar
        );

        return parent::prepare( $query, ...$args );
    }


    public function prepareAndReplaceTablePrefix(
        $query,
        ...$args
    ) {

        return $this->prepare( static::replaceTablePrefix( $query ), ...$args );

    }


    public function query( $query )
    {

        $return_val = parent::query( $query );

        if ( ! empty( $this->dbh ) )
        {

            if ( $this->use_mysqli )
            {
                if ( $this->dbh instanceof mysqli )
                {
                    $this->last_error_no = mysqli_errno( $this->dbh );
                }
                else
                {
                    // $dbh is defined, but isn't a real connection.
                    // Something has gone horribly wrong, let's try a reconnect.
                    $this->last_error_no = 2006;
                }
            }
            elseif ( is_resource( $this->dbh ) )
            {
                /**
                 * @noinspection PhpElementIsNotAvailableInCurrentPhpVersionInspection
                 * @noinspection PhpFullyQualifiedNameUsageInspection
                 */
                $this->last_error_no = \mysql_errno( $this->dbh );
            }
            else
            {
                $this->last_error_no = 2006;
            }
        }

        return $return_val;

    }


    public function queryAndReplaceTablePrefix( $query )
    {

        return $this->query( static::replaceTablePrefix( $query ) );
    }


    public function replaceAndReplaceTablePrefix(
        $table,
        $data,
        $format = null
    ) {

        return parent::replace( static::replaceTablePrefix( $table ), $data, $format );
    }


    public function updateAndReplaceTablePrefix(
        $table,
        $data,
        $where,
        $format = null,
        $where_format = null
    ) {

        return parent::update( static::replaceTablePrefix( $table ), $data, $where, $format, $where_format );
    }


    /**
     * @param          $result
     * @param          $output
     * @param  string  $keyName
     * @param  string  $prefix
     *
     * @return array|null
     * @throws \ErrorException
     */
    public static function &formatOutput(
        &$result,
        $output,
        $keyName = '',
        $prefix = ''
    ): ?array {

        if ( $result === null )
        {
            return $result;
        }

        $class = null;

        if (
            ! in_array(
                $output,
                [
                    OBJECT,
                    OBJECT_K,
                    ARRAY_K,
                    ARRAY_A,
                    ARRAY_N,
                ],
                true
            )
            && class_exists( $output )
        )
        {

            $class  = $output;
            $output = $keyName
                ? OBJECT_K
                : OBJECT;

        }

        switch ( strtoupper( $output ) )
        {
            // Back compat for OBJECT being previously case-insensitive.

        case OBJECT:
            // Return an integer-keyed array of row objects.
            break;

        case OBJECT_K:
        case ARRAY_K:
        case ARRAY_A:
        case ARRAY_N:
            $new_array = [];

            // Return an array of row objects with keys from column 1.
            // (Duplicates are discarded.)
            if ( $result )
            {

                array_walk(
                    $result,
                    static function (
                        $row,
                        $key
                    )
                    use
                    (
                        &
                        $new_array,
                        $output,
                        &
                        $keyName,
                        $prefix
                    )
                    {

                        $object_vars = get_object_vars( $row );

                        switch ( $output )
                        {
                            /** @noinspection PhpMissingBreakStatementInspection */
                        case ARRAY_K:
                            $object_vars =& $row;
                            // continue with next

                        case OBJECT_K:
                            switch ( true )
                            {
                            case is_string( $key ):
                                // keep current key
                                break;

                            case empty( $keyName ):
                                $key = $prefix . reset( $object_vars );
                                break;

                            default:
                                $keyNames = (array) $keyName;
                                $key      = null;

                                foreach ( $keyNames as $keyName )
                                {
                                    if ( array_key_exists( $keyName, $object_vars ) )
                                    {
                                        $key = $prefix . $object_vars[ $keyName ];
                                        break;
                                    }

                                    if ( is_object( $row ) && property_exists( $row, $keyName ) )
                                    {
                                        $key = $prefix . $row->$keyName;
                                        break;
                                    }
                                }

                                if ( $key === null )
                                {
                                    throw new ErrorException(
                                        'Key not found in object: ' . implode( ', ', $keyNames )
                                    );
                                }
                            }

                            if ( ! isset( $new_array[ $key ] ) )
                            {
                                $new_array[ $key ] = $row;
                            }
                            break;

                        case ARRAY_A:
                            // Return an integer-keyed array of...
                            // ...column name-keyed row arrays.
                            $new_array[] = $object_vars;
                            break;

                        case ARRAY_N:
                            // Return an integer-keyed array of...
                            // ...integer-keyed row arrays.
                            $new_array[] = array_values( $object_vars );
                            break;
                        }
                    }
                );

            }

            $result = $new_array;
            unset( $new_array );
            break;

        default:
            throw new ErrorException( "Unknown output format or class '$output'" );
        }

        if ( $class !== null || ! empty( array_filter( array_column( $result, '__CLASS__' ) ) ) )
        {

            array_walk(
                $result,
                static function ( &$item ) use
                (
                    $class
                )
                {

                    $class = $item->__CLASS__ ?? $class;

                    if ( ! $item instanceof $class )
                    {
                        $item = new $class( $item );
                    }
                }
            );

        }

        return $result;

    }


    /**
     *
     * Replaces all occurrences of "wp_" at the beginning of table names with the actual prefix used on this
     * installation.
     *
     * @see https://dev.mysql.com/doc/refman/8.0/en/identifiers.html
     *
     * @param  string  $sqlOrTableName  Full SQL string if quoted identifiers are used. Table name only, if no quotes
     *                                  are used.
     *
     * @return string                   SQL string with replaced prefixes.
     */
    public static function replaceTablePrefix( string $sqlOrTableName ): string
    {

        if ( Core::$wpdb->prefix === 'wp_' )
        {
            return $sqlOrTableName;
        }

        /**
         * Internally, identifiers are converted to and are stored as Unicode (UTF-8). The permissible Unicode characters in identifiers are those in the Basic Multilingual Plane (BMP). Supplementary characters are not permitted. Identifiers thus may contain these characters:
         *
         * Permitted characters in unquoted identifiers:
         * - ASCII:    [0-9,a-z,A-Z$_] (basic Latin letters, digits 0-9, dollar, underscore)
         * - Extended: U+0080 .. U+FFFF
         *
         * Permitted characters in quoted identifiers include the full Unicode Basic Multilingual Plane (BMP), except U+0000:
         * - ASCII:    U+0001 .. U+007F
         * - Extended: U+0080 .. U+FFFF
         *
         * ASCII NUL (U+0000) and supplementary characters (U+10000 and higher) are not permitted in quoted or unquoted identifiers.
         *
         * Identifiers may begin with a digit but unless quoted may not consist solely of digits.
         *
         * Database, table, and column names cannot end with space characters.
         *
         * The identifier quote character is the backtick (`)
         *
         * @TODO         Consider tables that are joined using the comma-syntax, rather then using the JOIN keyword
         * @TODO         Consider tables that are renamed, simple RENAME
         * @TODO         Consider tables that are renamed, multi RENAME
         * @TODO         Consider tables that are renamed, ALTER TABLE ... RENAME
         * @TODO         Consider database-qualified tables
         * @TODO         Consider table-qualified fields
         * @noinspection SpellCheckingInspection
         * @noinspection NotOptimalRegularExpressionsInspection
         */
        return preg_replace(
            <<<'PATTERN'
/
(?<pre>     (?# we capture everything befor the prefix, as variable lengts positive lookbehinds are not possible)
^\s*        (?# for unqoted identifiers, it must be the only string in the whole text. Hence it needs to start with whitespace only:)
|           (?# otherwise, it needs to be a quoted string, either at the beginning of the string or following
                FROM, JOIN, UPDATE, INSERT [INTO], REPLACE [INTO], DELETE, TRUNCATE, ANALIZE, CHECK, REPAIR, DROP
                -> case-insenitive! which is turned on and off with the i-flag
            )
    (?i)(?:
         \s(?:
             FROM
            |JOIN
        )
        |
        (?:^|;)(?:
             UPDATE     (?:\s+ LOW_PRIORITY)? (?:\s+ IGNORE)? 
            |INSERT     (?:\s+ (?: LOW_PRIORITY | DELAYED | HIGH_PRIORITY ))? (?:\s+ IGNORE)? (?:\s+ INTO)?
            |REPLACE    (?:\s+ (?: LOW_PRIORITY | DELAYED ))? (?:\s+ INTO)?
            |DELETE     (?:\s+ LOW_PRIORITY)? (?:\s+ QUICK)? (?:\s+ IGNORE)? \s+ FROM
            |CREATE     \s+ (?:TABLE|VIEW)
            |ALTER      \s+ (?:TABLE|VIEW)
            |DROP       \s+ (?:(?:TEMPORARY\s+)?TABLE|VIEW)(?:\s+IF\s+EXISTS)?
            |RENAME     \s+ TABLE
            |TRUNCATE   (?:\s+ TABLE)?
            |INTO       \s+ TABLE
            |ANALIZE
            |CHECK
            |REPAIR
        )
    )(?-i)\s+
    (`)     (?# the quote is captured, so we can use it as a condition later in the string)

)           (?# end of <pre>)

wp_         (?# the default prefix)

(?<post>    (?# for consistency, we also capture everything after the prefix, eventhough variable-length postive lookaheads are possible)

(?(2)       (?# Permitted characters in quoted identifiers)
            (?:[\x{0001}-\x{005F}\x{0061}-\x{007F}\x{0080}-\x{FFFF}]|``)+
            (?# exclude U+0060 - ` Grave accent, backtick - from single-character range and only allow double backticks 

|           (?# Permitted characters in unquoted identifiers)
            [0-9]?[a-zA-Z$_][0-9a-zA-Z$_]*
)

(?(2)       (?# a quoted string needs to end with a quote followed by a space or the end of text)
            `(?:\s|$)
|           (?# while an unquoted identifiyer may only be followed by whitespace)
            \s*$
)

)           (?# end of <post>)
/
x (?# eXtended: ignore whitespace)
u (?# unicode)
S (?# Study: extra analysis is performed )
PATTERN,
            Core::$wpdb->prefix,
            $sqlOrTableName
        );

    }

}
